name: CI/CD

on:
  push:

jobs:
  linting_testing:
    runs-on: ubuntu-latest
    name: Lint Python code and run tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install -d
      - name: Lint Python code
        run: pipenv run pylint ur_operator -E
      - name: Execute unit tests
        run: pipenv run pytest tests/test_unit.py
      - name: Set up kind cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          image: kindest/node:v1.19.1
      - name: Execute E2E tests
        env:
          UPTIMEROBOT_API_KEY: ${{ secrets.UPTIMEROBOT_API_KEY }}
        run: pipenv run pytest tests/test_e2e.py

  build_docker_image:
    runs-on: ubuntu-latest
    needs: linting_testing
    name: Build and push Docker image
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Docker image
        run: docker build . --tag ghcr.io/brennerm/uptimerobot-operator:${{ env.BRANCH_NAME }}
      - name: Push Docker image
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        run: docker push ghcr.io/brennerm/uptimerobot-operator:${{ env.BRANCH_NAME }}
